name: Docs Build and Publish

on:
  push:
    branches: [feature/**]
  pull_request:
    branches: [main]

jobs:
  generate-docs:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
      - name: DocFX Build
        run: docfx docs/docfx.json
        continue-on-error: false
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: doc-site
          path: "./_site"
